### PR TITLE
Breaking: Drop support for node < 4 (fixes #4)

### LINKED ISSUE #4: Drop support for node < 4
Since we dropped support for node < 4 in ESLint, and considering the new rule format was announced with the ESLint 3.0 release (when node <4 support was dropped), it should be okay to drop the support for eslint-transforms as well.

### PR DESCRIPTION
**Pull request by vitorbal**

### CODE REVIEW

**Comment by nzakas** [comment]
Maybe add a note to the README too?

**Comment by vitorbal** [comment]
Of course, good idea!

**Comment by vitorbal** [comment]
Added a note to the README.

**Comment by nzakas** [comment]
Lgtm

**Pull request merged**
