### PR TITLE
Upgrade: eslint-release@^0.10.1

### PR DESCRIPTION
**Pull request by platinumazure**
Ensures that the eslint-transforms release will automatically push to GitHub.

### CODE REVIEW

**Comment by platinumazure** [comment]
@kborchers Sorry to bother you-- not sure what the CLA error means here. Please let me know if I need to amend my commit or force-push.

**Comment by kborchers** [comment]
Hmm that's strange. Will look into it.

**Comment by kborchers** [comment]
@platinumazure you should be all set now ... a weird permissions issue according to the infra team. Let us know if you continue to have issues on this repo.

**Comment by platinumazure** [comment]
Thanks so much for looking at this so quickly, @kborchers! You rock!

**Pull request merged**
